config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :stats
  resources :players
  resources :coaches
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :team


  def name
    firstname + " " + lastname
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
    @is_admin = params[:admin]
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to @coach, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:firstname, :lastname, :yearstart, :team_id)
    end
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_form.html.erb
<%= form_with(model: coach, local: true) do |form| %>
  <% if coach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coach.errors.count, "error") %> prohibited this coach from being saved:</h2>

      <ul>
        <% coach.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :yearstart %>
    <%= form.number_field :yearstart %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coaches/edit.html.erb
<h1>Editing Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Show', @coach %> |
<%= link_to 'Back', coaches_path %>

app/views/coaches/index.html.erb
<style>div.search{margin-left:10px;}</style>
<p id="notice"><%= notice %></p>

<h1>Coaches</h1>

<table class="table table-striped table-hover"
  data-toggle="table"
  data-search="true"
  data-search-align="left">
  <thead class="thead-dark">
    <tr>
      <th scope="col" data-sortable="true">First Name</th>
      <th scope="col" data-sortable="true">Last Name</th>
      <th scope="col" data-sortable="true">Year Start</th>
      <th scope="col" data-sortable="true">Team</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coaches.each do |coach| %>
      <tr>
        <td><%= coach.firstname %></td>
        <td><%= coach.lastname %></td>
        <td><%= coach.yearstart %></td>
        <td><%= coach.team.city %></td>
        <td><%= link_to 'Detail View', coach %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %> 

app/views/coaches/new.html.erb
<h1>New Coach</h1>

<%= render 'form', coach: @coach %>

<%= link_to 'Back', coaches_path %>

app/views/coaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @coach.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @coach.lastname %>
</p>

<p>
  <strong>Year Start:</strong>
  <%= @coach.yearstart %>
</p>

<p>
  <strong>Team:</strong>
  <%= @coach.team.city %>
</p>
<div class="row m-2 mt-5">
  <div class="col-4"><%= link_to 'Home', root_path %></div>
  <div class="col-4"><%= link_to 'All Coaches', coaches_path %></div>
  <div class="col-5"><%= link_to 'Edit Coach', edit_coach_path(@coach) if @is_admin == 'nba' %></div>
</div>