config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :stats
  resources :players
  resources :coaches
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :stats
  has_many :endorsements

  def name
    firstname + " " + lastname
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all.order(:lastname)
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @is_admin = params[:admin]
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:firstname, :lastname, :position, :team_id, :twitter_handle, :twitter_num_followers, :instagram_handle, :instagram_num_followers)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :twitter_handle %>
    <%= form.text_field :twitter_handle %>
  </div>

  <div class="field">
    <%= form.label :twitter_num_followers %>
    <%= form.text_field :twitter_num_followers %>
  </div>

  <div class="field">
    <%= form.label :instagram_handle %>
    <%= form.text_field :instagram_handle %>
  </div>

  <div class="field">
    <%= form.label :instagram_num_followers %>
    <%= form.text_field :instagram_num_followers %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Home', root_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Position</th>
      <th>Team</th>
      <th>Twitter Handle</th>
      <th>Twitter Followers</th>
      <th>Instagram Handle</th>
      <th>Instagram Followers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.firstname %></td>
        <td><%= player.lastname %></td>
        <td><%= player.position %></td>
        <td><%= player.team_id %></td>
        <td><%= player.twitter_handle %></td>
        <td><%= player.twitter_num_followers %></td>
        <td><%= player.instagram_handle %></td>
        <td><%= player.instagram_num_followers %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row m-2">
    <h2>Players Details</h2>
  </div>
  <div class="row m-2">
    <div class="col-6 col-md-3 p-1">First Name: <%= @player.firstname %></div>
    <div class="col-6 col-md-3 p-1">Last Name: <%= @player.lastname %></div>
    <div class="col-6 col-md-3 p-1">Position: <%= @player.position %></div>
    <div class="col-6 col-md-3 p-1">Team: <%= link_to @player.team.city, @player.team %></div>
    <div class="col-6 col-md-3 p-1">Twitter: <a href="https://www.twitter.com/<%= @player.twitter_handle%>" > <%= @player.twitter_handle%> </a></div>
    <div class="col-6 col-md-3 p-1">Twitter Followers: <%= @player.twitter_num_followers %></div>
    <div class="col-6 col-md-3 p-1">Instagram: <a href="https://www.instagram.com/<%= @player.instagram_handle %>"><%= @player.instagram_handle %> </a></div>
    <div class="col-6 col-md-3 p-1">Instagram Followers: <%= @player.instagram_num_followers %></div>
  </div>

  <div class="row m-2 mt-4">
    <h3>Players Stats</h3>
  </div>
  <div class="row m-2">
  <% @player.stats.each do |stat| %>
    <div class="col-6 col-md-3 p-1">Games Played: <%= stat.games_played %></div>
    <div class="col-6 col-md-3 p-1">PPG: <%= stat.ppg %></div>
    <div class="col-6 col-md-3 p-1">APG: <%= stat.apg %></div>
    <div class="col-6 col-md-3 p-1">RPG: <%= stat.rpg %></div>
    <div class="col-6 col-md-3 p-1">MPG: <%= stat.mpg %></div>
    <div class="col-6 col-md-3 p-1">PER: <%= stat.per %></div>
    <div class="col-6 col-md-3 p-1">FG: <%= stat.fg %></div>
    <div class="col-6 col-md-3 p-1">FT: <%= stat.ft %></div>
    <div class="col-6 col-md-3 p-1"><%= link_to 'Edit',edit_stat_path(stat) if @is_admin == 'nba' %></div>
  <% end %>
  </div>

  <div class="row m-2 mt-4">
    <h3>Players Endorsements</h3>
  </div>
  <div class="row m-2">
  <% @player.endorsements.each do |endorsement| %>
    <div class="col-3">Brand: <%= endorsement.brand %></div>
    <div class="col-8">Notes: <%= endorsement.notes %></div>
    <div class="col-1"><%= link_to 'Edit',edit_endorsement_path(endorsement) if @is_admin == 'nba' %></div>
  <% end.empty? and begin %>
    <div class="col-12">No Endorsements Found</div>
  <% end %>
  </div>
  <div class="row m-2 mt-5">
    <div class="col-6"><%= link_to 'Home', root_path %></div>
    <div class="col-6"><%= link_to 'Edit Player', edit_player_path(@player) if @is_admin == 'nba' %></div>
  </div>