config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :stats
  resources :players
  resources :coaches
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :player
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

  # GET /endorsements
  # GET /endorsements.json
  def index
    @endorsements = Endorsement.all
    @is_admin = params[:admin]
  end

  # GET /endorsements/1
  # GET /endorsements/1.json
  def show
    @is_admin = params[:admin]
  end

  # GET /endorsements/new
  def new
    @endorsement = Endorsement.new
  end

  # GET /endorsements/1/edit
  def edit
  end

  # POST /endorsements
  # POST /endorsements.json
  def create
    @endorsement = Endorsement.new(endorsement_params)

    respond_to do |format|
      if @endorsement.save
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully created.' }
        format.json { render :show, status: :created, location: @endorsement }
      else
        format.html { render :new }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endorsements/1
  # PATCH/PUT /endorsements/1.json
  def update
    respond_to do |format|
      if @endorsement.update(endorsement_params)
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully updated.' }
        format.json { render :show, status: :ok, location: @endorsement }
      else
        format.html { render :edit }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endorsements/1
  # DELETE /endorsements/1.json
  def destroy
    @endorsement.destroy
    respond_to do |format|
      format.html { redirect_to endorsements_url, notice: 'Endorsement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endorsement_params
      params.require(:endorsement).permit(:brand, :notes, :player_id)
    end
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/endorsements/_form.html.erb
<%= form_with(model: endorsement, local: true) do |form| %>
  <% if endorsement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(endorsement.errors.count, "error") %> prohibited this endorsement from being saved:</h2>

      <ul>
        <% endorsement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.number_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/endorsements/edit.html.erb
<h1>Editing Endorsement</h1>

<%= render 'form', endorsement: @endorsement %>

<%= link_to 'Show', @endorsement %> |
<%= link_to 'Home', root_path %>

app/views/endorsements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Endorsements</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Notes</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endorsements.each do |endorsement| %>
      <tr>
        <td><%= endorsement.brand %></td>
        <td><%= endorsement.notes %></td>
        <td><%= endorsement.player_id %></td>
        <td><%= link_to 'Show', endorsement %></td>
        <td><%= link_to 'Edit', edit_endorsement_path(endorsement) if @is_admin == 'nba'%></td>
        <td><%= link_to 'Destroy', endorsement, method: :delete, data: { confirm: 'Are you sure?' } if @is_admin == 'nba'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endorsement', new_endorsement_path %>

app/views/endorsements/new.html.erb
<h1>New Endorsement</h1>

<%= render 'form', endorsement: @endorsement %>

<%= link_to 'Back', endorsements_path %>

app/views/endorsements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @endorsement.brand %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @endorsement.notes %>
</p>

<p>
  <strong>Player:</strong>
  <%= @endorsement.player_id %>
</p>
<div class="row m-2 mt-5">
  <div class="col-4"><%= link_to 'Home', root_path %></div>
  <div class="col-4"><%= link_to 'All Endorsements', endorsements_path %></div>
  <div class="col-4"><%= link_to 'Edit', edit_endorsement_path(@endorsement) if @is_admin == 'nba' %></div>
</div>