config/routes.rb
Rails.application.routes.draw do
  resources :endorsements
  resources :stats
  resources :players
  resources :coaches
  resources :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :player
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
    @is_admin = params[:admin]
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
    @is_admin = params[:admin]
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.require(:stat).permit(:games_played, :ppg, :apg, :rpg, :mpg, :per, :fg, :ft, :player_id)
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/_form.html.erb
<%= form_with(model: stat, local: true) do |form| %>
  <% if stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
        <% stat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :games_played %>
    <%= form.number_field :games_played %>
  </div>

  <div class="field">
    <%= form.label :ppg %>
    <%= form.text_field :ppg %>
  </div>

  <div class="field">
    <%= form.label :apg %>
    <%= form.text_field :apg %>
  </div>

  <div class="field">
    <%= form.label :rpg %>
    <%= form.text_field :rpg %>
  </div>

  <div class="field">
    <%= form.label :mpg %>
    <%= form.text_field :mpg %>
  </div>

  <div class="field">
    <%= form.label :per %>
    <%= form.text_field :per %>
  </div>

  <div class="field">
    <%= form.label :fg %>
    <%= form.text_field :fg %>
  </div>

  <div class="field">
    <%= form.label :ft %>
    <%= form.text_field :ft %>
  </div>

  <div class="field">
    <%= form.label :player_id %>
    <%= form.number_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing Stat</h1>

<%= render 'form', stat: @stat %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Home', root_path %>

app/views/stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stats</h1>

<table>
  <thead>
    <tr>
      <th>Games played</th>
      <th>Ppg</th>
      <th>Apg</th>
      <th>Rpg</th>
      <th>Mpg</th>
      <th>Per</th>
      <th>Gf</th>
      <th>Ft</th>
      <th>Player Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.games_played %></td>
        <td><%= stat.ppg %></td>
        <td><%= stat.apg %></td>
        <td><%= stat.rpg %></td>
        <td><%= stat.mpg %></td>
        <td><%= stat.per %></td>
        <td><%= stat.fg %></td>
        <td><%= stat.ft %></td>
        <td><%= stat.player_id %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) if @is_admin == 'nba'%></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } if @is_admin == 'nba'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New Stat</h1>

<%= render 'form', stat: @stat %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Games Played:</strong>
  <%= @stat.games_played %>
</p>

<p>
  <strong>PPG:</strong>
  <%= @stat.ppg %>
</p>

<p>
  <strong>APG:</strong>
  <%= @stat.apg %>
</p>

<p>
  <strong>RPG:</strong>
  <%= @stat.rpg %>
</p>

<p>
  <strong>MPG:</strong>
  <%= @stat.mpg %>
</p>

<p>
  <strong>PER:</strong>
  <%= @stat.per %>
</p>

<p>
  <strong>FG:</strong>
  <%= @stat.fg %>
</p>

<p>
  <strong>FT:</strong>
  <%= @stat.ft %>
</p>

<p>
  <strong>Player ID:</strong>
  <%= @stat.player_id %>
</p>
<div class="row m-2 mt-5">
  <div class="col-4"><%= link_to 'Home', root_path %></div>
  <div class="col-4"><%= link_to 'Edit Stat', edit_stat_path(@stat) if @is_admin == 'nba'%></div>
</div>